### ISSUE TITLE
修改个人信息时的BUG

### ISSUE THREAD

**Issue by tmw1996** [EAGzzyCSL/ApplicationPracticeDoc#1]
修改个人信息时，无法对姓名进行修改，如图，点击姓名时操作无效
![screenshot_2016-09-16-11-39-45](https://cloud.githubusercontent.com/assets/21305674/18574714/7a1579c2-7c02-11e6-921f-9b91a9e7719c.png)

**Comment by ZCJuncture** [comment]
这个姓名到底是用户名还是昵称，这点一直不是很清楚，因为user表里和user_info表里都有，但是我平时得到的数据都是user表的，只有这个页面孤立在user_info表中，改了在别的页面也看不见，所以索性就把这个当作用户名，只是显示而不允许更改。
